Website = "https://patenaude.io/"

[Details]
  Icon = "Icon.png"
  Name = "GooeyLife"
  ID = "io.patenaude.gooeylife"
  Version = "0.1.1"
  Build = 5

[LinuxAndBSD]
  GenericName = "Game of Life"
  Categories = ["Games"]
  Comment = "Run simulations of Conway's Game of Life"
  Keywords = ["life", "game"]
