Website = "https://patenaude.io/"

[Details]
  Icon = "Icon.png"
  Name = "GooeyLife"
  ID = "io.patenaude.gooeylife"
  Version = "0.1.7"
  Build = 54

[LinuxAndBSD]
  GenericName = "Game of Life"
  Categories = ["Game"]
  Comment = "Run simulations of Conway's Game of Life"
  Keywords = ["life", "game"]
